### ISSUE TITLE
Poor explanation - not clear on how to use Adaptive cards to customize search results

### ISSUE THREAD

**Issue by vradichkova** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#273] opened 2022-06-22 17:50 UTC
Poor explanation, no proper links to Layout designer, and no step by step directions.  I find it very frustrating weeding through the documentation, trying to find a video that hopefully a blogger has posted on the topic that explains the material.  The MS videos are not well explained, maybe because they are done by engineers who live and breathe this topic, and cannot step back and put themselves in the shoes of people who hear for the first time about a new feature/product, etc.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed997b94-55a7-1a7f-ff29-869039a91ce4
* Version Independent ID: e95ff5ad-2872-7269-7b8d-ed3221b806cf
* Content: [Manage search result layouts](https://docs.microsoft.com/en-us/microsoftsearch/customize-results-layout)
* Content Source: [MicrosoftSearch/customize-results-layout.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/customize-results-layout.md)
* Service: **mssearch**
* GitHub Login: @jypal6
* Microsoft Alias: **jypal**

**Comment by jypal6** [comment] 2022-07-04 09:57
Hi @vradichkova,
Thanks for your feedback and we will work towards improving the documentation to make the setup simpler. There is an introductory article with steps on customizing result layouts that can be found here - https://docs.microsoft.com/en-us/microsoftsearch/manage-result-types. A video explaining the basic feature setup can be found here - https://youtu.be/jKpIDBalLW0?t=844 
Do let us know if this is helpful.

**Comment by jypal6** [comment] 2022-07-11 04:54
Hope the issue is resolved. Closing this issue as there are no more follow up questions.

**Closed by jypal6** 2022-07-11 04:54 UTC
